# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MINT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MINT
  pod 'web3.swift'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya', '~> 15.0'
  pod 'lottie-ios'

  target 'MINTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MINTUITests' do
    # Pods for testing
  end

end
